---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.4
# Date:      Sat Sep 7 19:54:36 2024 -0600
#

#
# FireMyPi:  dnssettings.yml
#

#
# This playbook customizes the DNS settings.
#


- name: Create the dns directory
  file:
    dest: "{{var_ipfire}}/dns"
    state: directory

- name: Create the settings file
  template:
    src: "{{builddir}}/resource/dnssettings-settings.j2"
    dest: "{{var_ipfire}}/dns/settings"

...
