---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.6
# Date:      Fri Oct 25 18:59:04 2024 -0600
#

#
# FireMyPi:  hosts.yml
#

#
# This playbook creates the 'hosts' configuration for hostnames
# specified in the nodeN_vars.yml file and nodeN.hosts files.
#


- name: Create main/temp directory
  file:
    dest: "{{var_ipfire}}/main/temp"
    state: directory
  when: hosts_mode != "off"

- name: Create hostnames as specified in node vars
  lineinfile:
    create: true
    path: "{{var_ipfire}}/main/temp/hosts.fragment1"
    line: "{{item.enabled}},{{item.ip}},{{item.hostname}},{{item.domain}},{{item.generate_ptr}}"
  loop: "{{hosts}}"
  when: hosts_mode == "hosts_var" or hosts_mode == "combined"

- name: Change "off" to "" for hosts not enabled
  replace:
    path: "{{var_ipfire}}/main/temp/hosts.fragment1"
    regexp: "^off"
    replace: ""
  when: hosts_mode == "hostnames_var" or hosts_mode == "combined"

- name: Check if hosts file exists
  stat:
    path: "{{builddir}}/config/{{prefix}}{{node}}.hosts"
  register: result

- name: Copy hostnames from hosts file
  copy:
    src: "{{builddir}}/config/{{prefix}}{{node}}.hosts"
    dest: "{{var_ipfire}}/main/temp/hosts.fragment2"
  when: result.stat.exists and (hosts_mode == "hosts_file" or hosts_mode == "combined")

- name: Assemble fixleases file
  assemble:
    src: "{{var_ipfire}}/main/temp"
    dest: "{{var_ipfire}}/main/hosts"
  when: hosts_mode != "off"

- name: Delete temp directory
  file:
    path: "{{var_ipfire}}/main/temp"
    state: absent
  when: hosts_mode != "off"

- name: Sort and remove duplicates from hosts
  command:
    chdir: "{{var_ipfire}}/main"
    cmd: "sort -t . -u -k 3,3n -k 4,4n hosts -o hosts"
  when: hosts_mode != "off"

...
