---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.6
# Date:      Fri Oct 25 18:59:04 2024 -0600
#

#
# FireMyPi:  logging.yml
#

#
# This playbook creates the log settings configuration.
#


- name: Get log settings
  include_vars:
    file: "{{builddir}}/config/logging.yml"

- name: Create the logging directory
  file:
    path: "{{var_ipfire}}/logging"
    state: directory

- name: copy logging configuration file
  template:
    src: "{{builddir}}/resource/logging-settings.j2"
    dest: "{{var_ipfire}}/logging/settings"

...
