---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.6
# Date:      Fri Oct 25 18:59:04 2024 -0600
#

#
# FireMyPi:  main-settings.yml
#

#
# Set up basic things like hostname, timezone, language.
# Set IPFire Web GUI password.
#


- name: Create main directory
  file:
    path: "{{var_ipfire}}/main"
    state: directory

- name: Configure ipfire main settings
  template:
    src: "{{builddir}}/resource/main-settings.j2"
    dest: "{{var_ipfire}}/main/settings"

- name: Create fireinfo flag file to enable
  file:
    dest: "{{var_ipfire}}/main/send_profile"
    state: touch
  when: include_fireinfo

- name: Create auth directory
  file:
    path: "{{var_ipfire}}/auth"
    state: directory

- name: Get Web GUI admin password from file
  include_vars:
    file: "{{builddir}}/secrets/webadmin-secret.yml"

- name: Configure Web GUI admin password
  template:
    src: "{{builddir}}/resource/main-settings-users.j2"
    dest: "{{var_ipfire}}/auth/users"
    mode: '600'

...
