---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# List the dns servers to use if include_dnsaddservers is on.
#
#   These are global settings for all nodes.
#

    # This example sets the node to use the public 84 and 88 dns servers.
    dnsserver1: "8.8.4.4"
    dnsserver2: "8.8.8.8"

    # This example sets the node to use the same internal dns server
    # as is used by the dns clients.  The second dns server in this 
    # example is set all zeros as in non-existing.
    #dnsserver1: "192.168.{{node}}.{{green_dnsserver}}"
    #dnsserver2: "0.0.0.0"

...
