---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.4
# Date:      Sat Sep 7 19:54:36 2024 -0600
#

#
# FireMyPi:  ipblocklist.yml
#

#
# Configure the ipblocklist sources to include.  These settings will apply
# to all nodes with include_ipblocklist enabled.
#
# Use quoted "on" and "off" for all values so that ansible doesn't
# translate them to True and False.
#

    ipblocklist_enabled: "on"
    ipblocklist_log: "on"

    # See the Web GUI for more information on the blocklists
    # shown here.

    ipblocklists:

    - listname: "3CORESEC_SCAN"
      enable: "off"

    - listname: "3CORESEC_SSH"
      enable: "off"

    - listname: "3CORESEC_WEB"
      enable: "off"

    - listname: "ABUSECH_BOTNETC2"
      enable: "off"

    - listname: "BLOCKLIST_DE"
      enable: "on"

    - listname: "BOGON"
      enable: "off"

    - listname: "BOGON_FULL"
      enable: "on"

    - listname: "CIARMY"
      enable: "on"

    - listname: "DSHIELD"
      enable: "on"

    - listname: "EMERGING_COMPROMISED"
      enable: "off"

    - listname: "EMERGING_FWRULE"
      enable: "off"

    - listname: "FEODO_AGGRESSIVE"
      enable: "off"

    - listname: "FEODO_IP"
      enable: "off"

    - listname: "FEODO_RECOMMENDED"
      enable: "off"

    - listname: "SHODAN"
      enable: "off"

    - listname: "SPAMHAUS_DROP"
      enable: "on"

    - listname: "TOR_ALL"
      enable: "off"

    - listname: "TOR_EXIT"
      enable: "on"

...
