---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Global openvpn settings for all nodes.
#

    ovpn_enabled: "on"

    ovpn_country: "US"
    ovpn_org: "{{firemypi_hostname}}"
    ovpn_dcipher: "AES-256-GCM"

    ovpn_roadwarrior_enabled: true
    ovpn_roadwarrior:

      - index: 1
        offon: "on"
        name: "{{firemypi_hostname}}Admin"

          #      - index: 2
          #        offon: "on"
          #        name: "RemoteAdmin"

...
