---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.1
# Date:      Wed Jun 26 23:17:45 2024 -0600
#

#
# FireMyPi:  pakfire.yml
#

#
# List packages that you want pakfire to install on first boot.
#
# The package name is the "meta" name which does not include the version.
#
# For example, list "7zip" to install "7zip-17.05-10" that you see on
# the *IPFire/Pakfire* screen.
#
# Some utility examples are listed below.  Refer to the *IPFire/Pakfire*
# screen for the full list of available add-ons.
#

    pakfire_addons:

    - package: "7zip"
    - package: "rsync"
    - package: "speedtest-cli"

...
