---

##
## Copyright © 2020-2024 David Čuka and Stephen Čuka All Rights Reserved.
##
## FireMyPi is licensed under the Creative Commons Attribution-NonCommercial-
## NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
##
## The full text of the license can be found in the included LICENSE file 
## or at https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en.
##
## For the avoidance of doubt, FireMyPi is for personal use only and may not 
## be used by or for any business in any way.
##

#
# Version:   v1.1
# Date:      Wed Jun 26 23:17:45 2024 -0600
#

#
# FireMyPi:  vpnactivenodes.yml
#

#
# List the vpn nodes to configure and activate.
#
# The nodes that you activate here should all have 'include_vpn:'
# set to 'true' when they are built.
#

    vpnactivenodes:

    - vpnnode: 1
    - vpnnode: 2
    - vpnnode: 3

...
